openapi: 3.0.3
info:
  title: IP
  description: IP
  version: 1.0.0
servers:
  - url: 'https://api.delira.com'
    description: The production API server
    variables:
      username:
        # note! no enum here means it is an open value
        default: demo
        description: this value is assigned by the service provider, in this example `gigantic-server.com`
      port:
        enum:
          - '8443'
          - '443'
        default: '8443'
      basePath:
        # open meaning there is the opportunity to use special base paths as assigned by the provider, default is `v2`
        default: v1
paths:
  /ip:
    get:
      description: Returns all know information about the IP address
      responses:
        '200':
          description: A list of pets.

  
